capture:
  type: gopro_udp
  address: udp://0.0.0.0:8554

gpu:
  backend: opencl

ai:
  engine: onnxruntime
  model_path: assets/models/person-segmentation.onnx

pipeline:
  threads: auto
  queue_size: 4

filters:
  - type: fps_overlay
    enabled: true
    fps: 30.0
    x: 8
    y: 8
  - type: histogram
    enabled: true
    draw_overlay: false
    x: 8
    y: 32
    width: 64
    height: 32

output:
  type: v4l2
  device: /dev/video20
  pixel_format: RGB24
  width: 1280
  height: 720
  fps: 30
