capture:
  type: gopro_udp
  address: udp://0.0.0.0:8554

gpu:
  backend: opencl

ai:
  engine: onnxruntime
  model_path: assets/models/pphumanseg.onnx

pipeline:
  threads: auto
  queue_size: 4

output:
  type: v4l2
  device: /dev/video21
  pixel_format: RGB24
  width: 720
  height: 1280
  fps: 30
